from dataclasses import dataclass

from app.visual_engine.types import AnimationProfile, ColorProfile, GeometryProfile, TensionProfile


@dataclass(frozen=True)
class ElementVisualProfile:
    colors: ColorProfile
    tension: TensionProfile
    geometry: GeometryProfile
    animation: AnimationProfile
    glow: float
    contrast: float
    complexity: float
    ripple_strength: float
    beam_strength: float
    grain: float
    particle_density: float


@dataclass(frozen=True)
class MoodAxes:
    valence: float
    arousal: float
    luminosity: float
    grit: float


PROFILE_LIBRARY: dict[str, ElementVisualProfile] = {
    "major": ElementVisualProfile(
        colors=ColorProfile("#f7d56b", "#ffd8a8", "#130f10", "warm"),
        tension=TensionProfile(level=2, intensity=0.22, label="low"),
        geometry=GeometryProfile("soft-orb", orb=0.86, wave=0.34, fracture=0.12, lattice=0.18),
        animation=AnimationProfile("flowing", energy=0.58, motion_speed=0.46),
        glow=0.62,
        contrast=0.34,
        complexity=0.28,
        ripple_strength=0.32,
        beam_strength=0.22,
        grain=0.16,
        particle_density=0.34,
    ),
    "minor": ElementVisualProfile(
        colors=ColorProfile("#7488ff", "#99b0ff", "#0e1020", "cool"),
        tension=TensionProfile(level=5, intensity=0.56, label="medium"),
        geometry=GeometryProfile("wave", orb=0.24, wave=0.78, fracture=0.18, lattice=0.22),
        animation=AnimationProfile("calm", energy=0.42, motion_speed=0.36),
        glow=0.48,
        contrast=0.48,
        complexity=0.44,
        ripple_strength=0.62,
        beam_strength=0.26,
        grain=0.24,
        particle_density=0.42,
    ),
    "pentatonic": ElementVisualProfile(
        colors=ColorProfile("#00d7ff", "#7a7bff", "#081521", "cool"),
        tension=TensionProfile(level=3, intensity=0.34, label="low"),
        geometry=GeometryProfile("lattice", orb=0.22, wave=0.38, fracture=0.14, lattice=0.82),
        animation=AnimationProfile("flowing", energy=0.66, motion_speed=0.62),
        glow=0.64,
        contrast=0.56,
        complexity=0.52,
        ripple_strength=0.36,
        beam_strength=0.48,
        grain=0.22,
        particle_density=0.48,
    ),
    "harmonic minor": ElementVisualProfile(
        colors=ColorProfile("#df4f74", "#7d1f4e", "#15060d", "dark"),
        tension=TensionProfile(level=8, intensity=0.88, label="high"),
        geometry=GeometryProfile("fracture", orb=0.14, wave=0.44, fracture=0.86, lattice=0.26),
        animation=AnimationProfile("tense", energy=0.78, motion_speed=0.72),
        glow=0.7,
        contrast=0.78,
        complexity=0.72,
        ripple_strength=0.52,
        beam_strength=0.58,
        grain=0.44,
        particle_density=0.72,
    ),
    "melodic minor": ElementVisualProfile(
        colors=ColorProfile("#42c6b0", "#ff8a5b", "#081314", "cool"),
        tension=TensionProfile(level=6, intensity=0.66, label="medium"),
        geometry=GeometryProfile("wave", orb=0.24, wave=0.74, fracture=0.24, lattice=0.3),
        animation=AnimationProfile("flowing", energy=0.72, motion_speed=0.66),
        glow=0.68,
        contrast=0.58,
        complexity=0.62,
        ripple_strength=0.68,
        beam_strength=0.42,
        grain=0.22,
        particle_density=0.58,
    ),
    "ionian": ElementVisualProfile(
        colors=ColorProfile("#f8d66d", "#fff3bf", "#120f10", "warm"),
        tension=TensionProfile(level=2, intensity=0.2, label="low"),
        geometry=GeometryProfile("soft-orb", orb=0.88, wave=0.3, fracture=0.1, lattice=0.18),
        animation=AnimationProfile("flowing", energy=0.56, motion_speed=0.42),
        glow=0.58,
        contrast=0.3,
        complexity=0.24,
        ripple_strength=0.28,
        beam_strength=0.2,
        grain=0.16,
        particle_density=0.3,
    ),
    "dorian": ElementVisualProfile(
        colors=ColorProfile("#59d1a4", "#9af0dd", "#071516", "cool"),
        tension=TensionProfile(level=5, intensity=0.52, label="medium"),
        geometry=GeometryProfile("wave", orb=0.22, wave=0.82, fracture=0.12, lattice=0.34),
        animation=AnimationProfile("flowing", energy=0.64, motion_speed=0.58),
        glow=0.66,
        contrast=0.5,
        complexity=0.52,
        ripple_strength=0.76,
        beam_strength=0.34,
        grain=0.18,
        particle_density=0.5,
    ),
    "phrygian": ElementVisualProfile(
        colors=ColorProfile("#574062", "#d95f43", "#09070f", "dark"),
        tension=TensionProfile(level=7, intensity=0.78, label="high"),
        geometry=GeometryProfile("wave", orb=0.12, wave=0.68, fracture=0.42, lattice=0.18),
        animation=AnimationProfile("tense", energy=0.68, motion_speed=0.54),
        glow=0.46,
        contrast=0.74,
        complexity=0.64,
        ripple_strength=0.58,
        beam_strength=0.48,
        grain=0.42,
        particle_density=0.46,
    ),
    "lydian": ElementVisualProfile(
        colors=ColorProfile("#ffe56d", "#8fdcff", "#0f1117", "warm"),
        tension=TensionProfile(level=4, intensity=0.36, label="low"),
        geometry=GeometryProfile("soft-orb", orb=0.82, wave=0.42, fracture=0.12, lattice=0.24),
        animation=AnimationProfile("flowing", energy=0.74, motion_speed=0.58),
        glow=0.78,
        contrast=0.42,
        complexity=0.46,
        ripple_strength=0.62,
        beam_strength=0.42,
        grain=0.16,
        particle_density=0.46,
    ),
    "mixolydian": ElementVisualProfile(
        colors=ColorProfile("#ff9b35", "#ffd36b", "#171008", "warm"),
        tension=TensionProfile(level=5, intensity=0.5, label="medium"),
        geometry=GeometryProfile("lattice", orb=0.26, wave=0.42, fracture=0.18, lattice=0.74),
        animation=AnimationProfile("flowing", energy=0.7, motion_speed=0.62),
        glow=0.68,
        contrast=0.58,
        complexity=0.54,
        ripple_strength=0.38,
        beam_strength=0.52,
        grain=0.24,
        particle_density=0.56,
    ),
    "maj7": ElementVisualProfile(
        colors=ColorProfile("#ffb45c", "#ff89b5", "#160e0d", "warm"),
        tension=TensionProfile(level=3, intensity=0.3, label="low"),
        geometry=GeometryProfile("soft-orb", orb=0.9, wave=0.34, fracture=0.1, lattice=0.18),
        animation=AnimationProfile("flowing", energy=0.64, motion_speed=0.48),
        glow=0.86,
        contrast=0.4,
        complexity=0.34,
        ripple_strength=0.34,
        beam_strength=0.3,
        grain=0.14,
        particle_density=0.4,
    ),
    "min7": ElementVisualProfile(
        colors=ColorProfile("#7bdff2", "#85a8ff", "#081018", "cool"),
        tension=TensionProfile(level=4, intensity=0.42, label="medium"),
        geometry=GeometryProfile("wave", orb=0.24, wave=0.78, fracture=0.1, lattice=0.26),
        animation=AnimationProfile("calm", energy=0.46, motion_speed=0.4),
        glow=0.62,
        contrast=0.46,
        complexity=0.4,
        ripple_strength=0.62,
        beam_strength=0.28,
        grain=0.16,
        particle_density=0.46,
    ),
    "dominant7": ElementVisualProfile(
        colors=ColorProfile("#f25f5c", "#ffc145", "#16090b", "warm"),
        tension=TensionProfile(level=6, intensity=0.68, label="medium"),
        geometry=GeometryProfile("fracture", orb=0.16, wave=0.4, fracture=0.78, lattice=0.22),
        animation=AnimationProfile("tense", energy=0.78, motion_speed=0.68),
        glow=0.74,
        contrast=0.72,
        complexity=0.68,
        ripple_strength=0.44,
        beam_strength=0.58,
        grain=0.34,
        particle_density=0.64,
    ),
    "dim7": ElementVisualProfile(
        colors=ColorProfile("#d8f6ff", "#a6d0ff", "#06080c", "cool"),
        tension=TensionProfile(level=9, intensity=0.96, label="high"),
        geometry=GeometryProfile("fracture", orb=0.08, wave=0.32, fracture=0.92, lattice=0.28),
        animation=AnimationProfile("tense", energy=0.84, motion_speed=0.78),
        glow=0.72,
        contrast=0.88,
        complexity=0.84,
        ripple_strength=0.4,
        beam_strength=0.72,
        grain=0.5,
        particle_density=0.82,
    ),
    "aug": ElementVisualProfile(
        colors=ColorProfile("#ff6bcb", "#ff8a5b", "#160611", "warm"),
        tension=TensionProfile(level=8, intensity=0.9, label="high"),
        geometry=GeometryProfile("fracture", orb=0.12, wave=0.36, fracture=0.88, lattice=0.24),
        animation=AnimationProfile("explosive", energy=0.92, motion_speed=0.88),
        glow=0.8,
        contrast=0.86,
        complexity=0.8,
        ripple_strength=0.46,
        beam_strength=0.74,
        grain=0.36,
        particle_density=0.76,
    ),
    "ii-v-i": ElementVisualProfile(
        colors=ColorProfile("#b8f2e6", "#b8c4ff", "#091115", "cool"),
        tension=TensionProfile(level=5, intensity=0.48, label="medium"),
        geometry=GeometryProfile("wave", orb=0.34, wave=0.66, fracture=0.18, lattice=0.58),
        animation=AnimationProfile("flowing", energy=0.62, motion_speed=0.52),
        glow=0.68,
        contrast=0.46,
        complexity=0.6,
        ripple_strength=0.58,
        beam_strength=0.54,
        grain=0.18,
        particle_density=0.5,
    ),
    "i-v-vi-iv": ElementVisualProfile(
        colors=ColorProfile("#ffcf6e", "#ff9d8c", "#160f09", "warm"),
        tension=TensionProfile(level=3, intensity=0.28, label="low"),
        geometry=GeometryProfile("soft-orb", orb=0.82, wave=0.42, fracture=0.1, lattice=0.22),
        animation=AnimationProfile("flowing", energy=0.68, motion_speed=0.54),
        glow=0.7,
        contrast=0.34,
        complexity=0.46,
        ripple_strength=0.34,
        beam_strength=0.36,
        grain=0.18,
        particle_density=0.42,
    ),
}

DEFAULT_PROFILE = ElementVisualProfile(
    colors=ColorProfile("#7bdff2", "#8d99ff", "#091018", "cool"),
    tension=TensionProfile(level=5, intensity=0.5, label="medium"),
    geometry=GeometryProfile("lattice", orb=0.28, wave=0.42, fracture=0.24, lattice=0.6),
    animation=AnimationProfile("flowing", energy=0.58, motion_speed=0.5),
    glow=0.58,
    contrast=0.44,
    complexity=0.46,
    ripple_strength=0.42,
    beam_strength=0.34,
    grain=0.18,
    particle_density=0.42,
)

MOOD_LIBRARY: dict[str, MoodAxes] = {
    "major": MoodAxes(valence=0.78, arousal=0.52, luminosity=0.8, grit=0.16),
    "minor": MoodAxes(valence=0.36, arousal=0.34, luminosity=0.38, grit=0.28),
    "pentatonic": MoodAxes(valence=0.64, arousal=0.72, luminosity=0.62, grit=0.24),
    "harmonic minor": MoodAxes(valence=0.18, arousal=0.74, luminosity=0.28, grit=0.78),
    "melodic minor": MoodAxes(valence=0.58, arousal=0.68, luminosity=0.56, grit=0.42),
    "ionian": MoodAxes(valence=0.82, arousal=0.48, luminosity=0.82, grit=0.14),
    "dorian": MoodAxes(valence=0.52, arousal=0.56, luminosity=0.48, grit=0.22),
    "phrygian": MoodAxes(valence=0.14, arousal=0.66, luminosity=0.22, grit=0.72),
    "lydian": MoodAxes(valence=0.86, arousal=0.62, luminosity=0.88, grit=0.12),
    "mixolydian": MoodAxes(valence=0.68, arousal=0.72, luminosity=0.68, grit=0.28),
    "maj7": MoodAxes(valence=0.8, arousal=0.44, luminosity=0.78, grit=0.1),
    "min7": MoodAxes(valence=0.48, arousal=0.34, luminosity=0.46, grit=0.18),
    "dominant7": MoodAxes(valence=0.42, arousal=0.78, luminosity=0.56, grit=0.58),
    "dim7": MoodAxes(valence=0.08, arousal=0.88, luminosity=0.34, grit=0.86),
    "aug": MoodAxes(valence=0.32, arousal=0.92, luminosity=0.62, grit=0.74),
    "ii-v-i": MoodAxes(valence=0.58, arousal=0.54, luminosity=0.6, grit=0.26),
    "i-v-vi-iv": MoodAxes(valence=0.76, arousal=0.64, luminosity=0.74, grit=0.18),
}

DEFAULT_MOOD = MoodAxes(valence=0.56, arousal=0.58, luminosity=0.56, grit=0.28)
